# Generated by Django 5.1.4 on 2025-04-09 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_rename_bio_profilemodel_caption'),
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='Accounts.profilemodel'),
            preserve_default=False,
        ),
    ]
