# Generated by Django 5.1.4 on 2025-04-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0006_rename_comment_commentmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='likes',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='likes',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
