# Generated by Django 5.1.4 on 2025-04-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0007_remove_postmodel_likes_postmodel_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
