# Generated by Django 5.1.4 on 2025-04-09 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='bio',
            new_name='caption',
        ),
    ]
