# Generated by Django 5.1.4 on 2025-04-10 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_signupmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupmodel',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='signupmodel',
            name='password2',
        ),
    ]
